name: Sw Check - FileZilla
true:
  schedule:
  - cron: 30 9 * * *
  workflow_dispatch: null
jobs:
  swcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '
    - env:
        TGRAMCHATID: ${{ secrets.TGRAMCHATID }}
        TGRAMTOKEN: ${{ secrets.TGRAMTOKEN }}
      name: Check Software Update
      run: python sw_filezilla.py
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
        commit_message: Update FileZilla version file
        disable_globbing: true
        file_pattern: updates/*
        push_options: --force
        skip_checkout: true
        skip_dirty_check: false
        skip_fetch: true
