name: Sw Check - NAPS2

on:
  schedule:
  - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  swcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v4.2.2"
    - name: Set up Python 3.10
      uses: "actions/setup-python@v5.6.0"
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check Software Update
      run: python sw_naps2.py
      env:
        TGRAMTOKEN: ${{ secrets.TGRAMTOKEN }}
        TGRAMCHATID: ${{ secrets.TGRAMCHATID }}

    - name: Commit changes
      uses: "stefanzweifel/git-auto-commit-action@v5.1.0"
      with:
        commit_message: Update NAPS2 version file
        push_options: '--force'
        skip_dirty_check: false
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true
        file_pattern: updates/*
