name: Sw Check - XmlNotepad

on:
  schedule:
  - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check Software Update
      run: python sw_xmlnp.py
      env:
          TGRAMTOKEN: ${{ secrets.TGRAMTOKEN }}
          TGRAMCHATID: ${{ secrets.TGRAMCHATID }}
          
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update XmlNotepad version file
        push_options: '--force'
        skip_dirty_check: false
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true
        file_pattern: updates/*
